---
- name: Actualizar y hardenizar Ubuntu
  hosts: Ubuntu
  become: true

  tasks:
  - name: Actualizar paquetes
    ansible.builtin.apt:
      name: "*"
      state: latest
    notify: 
      - Reiniciar el equipo
      
  - name: Configurar Firewall
    community.general.ufw:
      state: enabled
      default: deny
      rule: allow
      port: ssh
      proto: tcp

  - name: Login con clave publica, root no puede login
    ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config.d/50-cloud-init.conf
      search_string: "PasswordAuthentication yes"
      state: present
      line: |
        PasswordAuthentication no 
        PermitRootLogin no
    notify: 
      - Reiniciar SSH

  - name: Instalar fail2ban
    ansible.builtin.package:
      name: fail2ban
      state: present

  - name: Configurar fail2ban
    ansible.builtin.copy:
      src: ../jail.local
      dest: /etc/fail2ban/jail.local

  - name: Iniciar y habilitar fail2ban
    ansible.builtin.service:
      name: fail2ban
      enabled: true
      state: started

  handlers: 
    - name: Reiniciar el equipo
      ansible.builtin.reboot:

    - name: Reiniciar SSH
      ansible.builtin.service:
        name: ssh
        state: restarted
